/** Друзья — граница и близость после шутки (см. ../AUTHORING.md) */
export default {
  id: "friends",
  title: "С друзьями",
  goal: "Сказать другу, что вам больно от его шутки, без обвинения в злом умысле.",
  estimatedMinutes: 22,
  sectionsOutline: [
    { id: "friends-situation", title: "Ситуация" },
    { id: "friends-observation", title: "Наблюдение" },
    { id: "friends-feeling", title: "Чувства" },
    { id: "friends-needs", title: "Потребности" },
    { id: "friends-request", title: "Просьба" },
    { id: "friends-integration", title: "Интеграция" },
  ],
  badge: {
    id: "badge-friends",
    label: "Дружеский Жираф",
    emoji: "🌉",
    giftTitle: "Мостик доверия",
    giftDescription: "Можно говорить о границах в шутках и оставаться в связи.",
  },
  steps: [
    {
      type: "theory_reveal",
      section: "friends-situation",
      sectionTitle: "Ситуация",
      title: "Шутка при компании",
      situation:
        "Друг пошутил про вас при компании. Вам не смешно, но стыдно «портить вечер». Что ближе к вашей первой реакции внутри?",
      options: [
        {
          id: "fr1",
          text: "«Он злой человек» — сразу ярлык.",
          quality: "poor",
          feedback: "Ярлык о друге — Волк; связь рвётся быстрее, чем шутка.",
        },
        {
          id: "fr2",
          text: "«Мне неловко и обидно» — честно про себя, без атаки личности.",
          quality: "best",
          feedback: "Чувство без обвинения — пространство для границы и просьбы.",
        },
        {
          id: "fr3",
          text: "Смеяться вместе с другими, хотя внутри не смешно.",
          quality: "ok",
          feedback: "Иногда так делают; цена — накопленная обида.",
        },
        {
          id: "fr4",
          text: "Сразу ударить шуткой в ответ про него.",
          quality: "ok",
          feedback: "Война шутками тоже ранит.",
        },
      ],
      afterReveal:
        "ННО не про молчание любой ценой — про честность без разрушения. Ниже — по шагам: факт, чувство, потребность, просьба.",
      body: `С друзьями можно сказать, что **больно или неловко**, и попросить **другой формат** шуток в будущем — без ломки дружбы одной фразой.\n\nДальше — упражнения в том же сценарии.`,
    },
    {
      type: "camera",
      section: "friends-observation",
      sectionTitle: "Наблюдение",
      title: "Факт",
      ofnrFocus: "observation",
      prompt: "Что из этого ближе к наблюдению?",
      options: [
        {
          id: "1",
          text: "Ты меня унизил(а).",
          correct: false,
          explain: "Интерпретация намерения.",
        },
        {
          id: "2",
          text: "Ты три раза повторил(а) шутку про мою работу.",
          correct: true,
          explain: "Счёт и содержание — то, что могла бы зафиксировать камера.",
        },
        {
          id: "3",
          text: "Ты вредный(ая).",
          correct: false,
          explain: "Оценка личности.",
        },
        {
          id: "4",
          text: "Все смеялись — значит шутка была удачной.",
          correct: false,
          explain: "Реакция группы — не описание вашего опыта.",
        },
      ],
    },
    {
      type: "select",
      section: "friends-observation",
      title: "Что произошло",
      ofnrFocus: "observation",
      prompt: "Как зафиксировать ситуацию без ярлыка «ты плохой друг»?",
      options: [
        {
          id: "o1",
          text: "Ты всегда издеваешься.",
          quality: "poor",
          feedback: "Обобщение.",
        },
        {
          id: "o2",
          text: "Когда прозвучала шутка про меня, остальные смеялись, а мне стало неловко.",
          quality: "best",
          feedback: "Факт и ваша реакция.",
        },
        {
          id: "o3",
          text: "Ты нормальный друг, просто я чувствительный.",
          quality: "ok",
          feedback: "Смягчение может скрывать границу.",
        },
        {
          id: "o4",
          text: "Ты специально меня подставил(а).",
          quality: "ok",
          feedback: "Догадка о намерении — не камера.",
        },
      ],
    },
    {
      type: "select",
      section: "friends-feeling",
      sectionTitle: "Чувства",
      title: "Мягкий старт",
      ofnrFocus: "feeling",
      prompt: "Как начать ближе к Жирафу?",
      options: [
        {
          id: "a",
          text: "Ты всегда такой злой.",
          quality: "poor",
          feedback: "«Всегда» и ярлык «злой».",
        },
        {
          id: "b",
          text: "Когда прозвучала шутка про меня, мне стало неловко и грустно.",
          quality: "best",
          feedback: "Факт + чувство без атаки личности.",
        },
        {
          id: "c",
          text: "Все смеялись, значит нормально.",
          quality: "ok",
          feedback: "Можно признать свою реакцию, даже если другим было смешно.",
        },
        {
          id: "d",
          text: "Ты меня предаёшь перед всеми.",
          quality: "ok",
          feedback: "Сильное слово без своего чувства в центре.",
        },
      ],
    },
    {
      type: "sort",
      section: "friends-needs",
      sectionTitle: "Потребности",
      title: "Волк или Жираф",
      ofnrFocus: "need",
      instructions: "Где слышно забота о доверии и границах?",
      items: [
        { id: "s1", text: "Ты обязан извиниться перед всеми.", answer: "wolf" },
        {
          id: "s2",
          text: "Мне важны уважение в шутке и честность между нами.",
          answer: "giraffe",
        },
        { id: "s3", text: "Ты плохой человек, раз так шутишь.", answer: "wolf" },
        {
          id: "s4",
          text: "Мне важно, чтобы я мог(ла) сказать, когда больно, без страха потерять друга.",
          answer: "giraffe",
        },
      ],
    },
    {
      type: "reflection",
      section: "friends-needs",
      title: "Пауза",
      prompt: "Что для вас важнее в этом разговоре — сохранить близость, назвать боль или оба варианта?",
      placeholder: "По желанию…",
    },
    {
      type: "dialog",
      section: "friends-request",
      sectionTitle: "Просьба",
      title: "Наедине после вечеринки",
      ofnrFocus: "request",
      start: "fd1",
      nodes: {
        fd1: {
          speaker: "them",
          text: "Да ладно тебе, это же шутка! Ты слишком серьёзный(ая).",
          choices: [
            {
              text: "Ты всегда всех унижаешь, ты токсик.",
              next: "fd2a",
              tone: "wolf",
            },
            {
              text: "Мне было неловко при всех. Мне важно, чтобы про мою работу не шутили без моего ок — можем так договориться?",
              next: "fd2b",
              tone: "giraffe",
            },
          ],
        },
        fd2a: {
          speaker: "them",
          text: "Слушай, если так, то и общаться не о чем.",
          choices: [{ text: "Пауза. Вернуться к фактам и чувству позже.", next: "end", tone: "neutral" }],
        },
        fd2b: {
          speaker: "them",
          text: "Ок, понял(а). Не знал(а), что задело. В следующий раз спрошу заранее или не буду про работу.",
          choices: [{ text: "Спасибо, что услышал(а).", next: "end", tone: "neutral" }],
        },
        end: {
          speaker: "them",
          text: "",
          choices: [],
        },
      },
    },
    {
      type: "select",
      section: "friends-request",
      title: "Просьба о границе",
      ofnrFocus: "request",
      prompt: "Какая просьба конкретна и уважает дружбу?",
      options: [
        {
          id: "r1",
          text: "Запрети всем смеяться надо мной.",
          quality: "poor",
          feedback: "Неконтролируемое требование.",
        },
        {
          id: "r2",
          text: "Можешь в следующий раз без шуток про мою работу или спросить, ок ли мне тема?",
          quality: "best",
          feedback: "Конкретика и выбор.",
        },
        {
          id: "r3",
          text: "Больше никогда не шути.",
          quality: "ok",
          feedback: "Абсолют без гибкости.",
        },
        {
          id: "r4",
          text: "Если не согласишься — дружбы нет.",
          quality: "ok",
          feedback: "Ультиматум вместо просьбы.",
        },
      ],
    },
    {
      type: "body_swap",
      section: "friends-integration",
      sectionTitle: "Интеграция",
      title: "Глазами друга",
      characterName: "Друг",
      yourPhrases: [
        "«Ты токсик» — слышится ярлык и конец доверия.",
        "«Мне неловко… можем договориться?» — слышится граница без разрушения личности.",
      ],
      contactStart: 52,
      highlights: [
        {
          fragment: "токсик",
          note: "Ярлык закрывает слушание",
          innerThought: "Меня вычеркнули — защищаюсь или ухожу.",
          contactDelta: -17,
        },
        {
          fragment: "Мне важно",
          note: "Слышу ценность, не только упрёк",
          innerThought: "Можно подумать, не нападать сразу.",
          contactDelta: 13,
        },
      ],
      theirPerspective:
        "Когда слышу ярлык — хочется отдалиться. Когда слышу чувство и просьбу — легче остаться в связи.",
    },
    {
      type: "build",
      section: "friends-integration",
      title: "Собери просьбу",
      ofnrFocus: "request",
      instructions: "Подберите блоки к слотам.",
      slots: [
        { key: "observation", label: "Наблюдение" },
        { key: "feeling", label: "Чувство" },
        { key: "need", label: "Потребность" },
        { key: "request", label: "Просьба" },
      ],
      bank: [
        { id: "o1", slot: "observation", text: "Шутка про меня прозвучала дважды за вечер." },
        { id: "o2", slot: "observation", text: "Ты плохой друг." },
        { id: "f1", slot: "feeling", text: "Мне стало неловко и обидно." },
        { id: "f2", slot: "feeling", text: "Ты должен страдать." },
        { id: "n1", slot: "need", text: "Мне важны уважение и доверие в нашем юморе." },
        { id: "n2", slot: "need", text: "Мне нужно победить спор." },
        { id: "r1", slot: "request", text: "Можешь в следующий раз без шуток про мою работу или спросить, границы ок?" },
        { id: "r2", slot: "request", text: "Запрети всем смеяться." },
      ],
      correct: {
        observation: "o1",
        feeling: "f1",
        need: "n1",
        request: "r1",
      },
    },
    {
      type: "reflection",
      section: "friends-integration",
      title: "Итог",
      prompt: "Одна фраза, которую хотите попробовать с другом, если снова заденет шутка?",
      placeholder: "По желанию…",
    },
  ],
};
