/** Общественный транспорт — коротко, вежливо, по делу (см. ../AUTHORING.md) */
export default {
  id: "transit",
  title: "В транспорте",
  goal: "Попросить человека сделать громкость музыки тише, сохраняя уважение к его автономии.",
  estimatedMinutes: 20,
  sectionsOutline: [
    { id: "transit-situation", title: "Ситуация" },
    { id: "transit-observation", title: "Наблюдение" },
    { id: "transit-feeling", title: "Чувства" },
    { id: "transit-needs", title: "Потребности" },
    { id: "transit-request", title: "Просьба" },
    { id: "transit-integration", title: "Интеграция" },
  ],
  badge: {
    id: "badge-transit",
    label: "Транспортный Жираф",
    emoji: "🎧",
    giftTitle: "Наушники гармонии",
    giftDescription: "Символ уважения к своему пространству и чужому.",
  },
  steps: [
    {
      type: "theory_reveal",
      section: "transit-situation",
      sectionTitle: "Ситуация",
      title: "Громко в наушниках",
      situation:
        "В вагоне сосед слушает музыку так громко, что вы слышите бит через свои наушники. Времени на лекцию нет. Что выберете как первый внутренний ориентир?",
      options: [
        {
          id: "tr1",
          text: "«Все вокруг невоспитанные» — обобщить и разозлиться.",
          quality: "poor",
          feedback: "Обобщение без конкретной просьбы — контакт не строится.",
        },
        {
          id: "tr2",
          text: "Короткий факт + вежливая просьба к этому человеку, без оскорблений.",
          quality: "best",
          feedback: "В транспорте срабатывает наблюдение + просьба с уважением к автономии.",
        },
        {
          id: "tr3",
          text: "Терпеть молча и строить монолог в голове.",
          quality: "ok",
          feedback: "Знакомо многим; граница и потребность остаются без голоса.",
        },
        {
          id: "tr4",
          text: "Снять наушники и смотреть с ненавистью, не говоря.",
          quality: "ok",
          feedback: "Напряжение растёт без ясной просьбы.",
        },
      ],
      afterReveal:
        "Здесь нет «продолжить завтра» — реакция быстрая. Ниже — факт, чувство, потребность, короткая просьба.",
      body: `Важны **короткий факт**, **вежливость** и **конкретная просьба** — без лекции. В вагоне часто хватает **наблюдения + просьбы** с уважением к чужой автономии.`,
    },
    {
      type: "camera",
      section: "transit-observation",
      sectionTitle: "Наблюдение",
      title: "Факт в вагоне",
      ofnrFocus: "observation",
      prompt: "Что ближе к наблюдению без оценки людей?",
      options: [
        {
          id: "c1",
          text: "Ты хам и невоспитанный.",
          correct: false,
          explain: "Ярлык.",
        },
        {
          id: "c2",
          text: "Я слышу музыку из ваших наушников — для меня она очень громкая, даже когда я не включаю свою.",
          correct: true,
          explain: "Факт: чужой звук слышен и мешает, без ярлыка о человеке.",
        },
        {
          id: "c3",
          text: "Все в вагоне тупые.",
          correct: false,
          explain: "Обобщение.",
        },
        {
          id: "c4",
          text: "Ты специально меня достаёшь.",
          correct: false,
          explain: "Догадка о намерении.",
        },
      ],
    },
    {
      type: "select",
      section: "transit-observation",
      title: "Коротко о факте",
      ofnrFocus: "observation",
      prompt: "Как зафиксировать ситуацию одной фразой?",
      options: [
        {
          id: "o1",
          text: "Из ваших наушников слышен бит — для меня он слишком отчётливый.",
          quality: "best",
          feedback: "Конкретный факт о том, что слышно.",
        },
        {
          id: "o2",
          text: "Люди в метро все невоспитанные.",
          quality: "poor",
          feedback: "Обобщение.",
        },
        {
          id: "o3",
          text: "Вы меня бесите.",
          quality: "ok",
          feedback: "Скорее эмоция и оценка.",
        },
        {
          id: "o4",
          text: "Наверное, вам нравится мне мешать.",
          quality: "ok",
          feedback: "Догадка о мотиве.",
        },
      ],
    },
    {
      type: "select",
      section: "transit-feeling",
      sectionTitle: "Чувства",
      title: "Что с вами",
      ofnrFocus: "feeling",
      prompt: "Как назвать своё состояние честно и коротко?",
      options: [
        {
          id: "f1",
          text: "Мне хочется вас ударить.",
          quality: "poor",
          feedback: "Импульс насилия — не безопасная формулировка для просьбы.",
        },
        {
          id: "f2",
          text: "Мне некомфортно от громкого звука и тяжело сосредоточиться.",
          quality: "best",
          feedback: "Чувство без атаки.",
        },
        {
          id: "f3",
          text: "Мне всё равно.",
          quality: "ok",
          feedback: "Если так не чувствуете — может скрывать злость.",
        },
        {
          id: "f4",
          text: "Я злюсь, когда не могу сосредоточиться.",
          quality: "best",
          feedback: "Чувство в ответ на ситуацию.",
        },
      ],
    },
    {
      type: "sort",
      section: "transit-needs",
      sectionTitle: "Потребности",
      title: "Волк или Жираф",
      ofnrFocus: "need",
      instructions: "Для каждой фразы нажмите «Волк» или «Жираф».",
      items: [
        { id: "t1", text: "Ты мешаешь всем в вагоне!", answer: "wolf" },
        { id: "t2", text: "Мне важен покой в дороге — можете сделать тише, пожалуйста?", answer: "giraffe" },
        { id: "t3", text: "С такими, как ты, невозможно жить.", answer: "wolf" },
        {
          id: "t4",
          text: "Мне важно иметь возможность читать и не перегружать уши чужим звуком.",
          answer: "giraffe",
        },
      ],
    },
    {
      type: "reflection",
      section: "transit-needs",
      title: "Пауза",
      prompt: "Если человек ответит грубо — что вы хотите сохранить в себе: спокойствие, границу или оба варианта?",
      placeholder: "По желанию…",
    },
    {
      type: "dialog",
      section: "transit-request",
      sectionTitle: "Просьба",
      title: "Обратиться к соседу",
      ofnrFocus: "request",
      start: "t1",
      nodes: {
        t1: {
          speaker: "them",
          messages: ["👂 А?", "❓ Что случилось?"],
          choices: [
            {
              text: "😡 Да ты что, оглох? Выруби немедленно!",
              next: "t2a",
              tone: "wolf",
            },
            {
              text: "🙏 Извините, слышу музыку из наушников очень громко. Можете чуть уменьшить громкость?",
              next: "t2b",
              tone: "giraffe",
            },
          ],
        },
        t2a: {
          speaker: "them",
          messages: ["🚶 Сам иди в другой вагон."],
          choices: [{ text: "🛑 Остановиться. При необходимости — перейти в другой вагон или обратиться к сотруднику транспорта.", next: "end", tone: "neutral" }],
        },
        t2b: {
          speaker: "them",
          messages: ["😌 А, понял(а).", "🙏 Извини, не заметил(а)."],
          choices: [{ text: "🙏 Спасибо.", next: "t3b", tone: "giraffe" }],
        },
        t3b: {
          speaker: "them",
          messages: ["🔉 Сейчас уберу громкость."],
          choices: [{ text: "👍 Хорошо.", next: "end", tone: "neutral" }],
        },
        end: {
          speaker: "them",
          text: "",
          choices: [],
        },
      },
    },
    {
      type: "select",
      section: "transit-request",
      title: "Короткая реплика",
      ofnrFocus: "request",
      prompt: "Что звучит уважительнее?",
      options: [
        {
          id: "a",
          text: "Ты что, глухой? Выключи это немедленно!",
          quality: "poor",
          feedback: "Оскорбление и требование.",
        },
        {
          id: "b",
          text: "Извините, слышу музыку из наушников очень громко. Можете чуть уменьшить громкость?",
          quality: "best",
          feedback: "Факт + просьба с «извините».",
        },
        {
          id: "c",
          text: "Люди вокруг совсем без культуры.",
          quality: "ok",
          feedback: "Обобщение без конкретной просьбы.",
        },
        {
          id: "d",
          text: "У вас там целый концерт, хватит.",
          quality: "ok",
          feedback: "Ирония вместо прямой просьбы.",
        },
      ],
    },
    {
      type: "body_swap",
      section: "transit-integration",
      sectionTitle: "Интеграция",
      title: "На месте соседа",
      characterName: "Сосед",
      yourPhrases: [
        "«Ты глухой» — слышится оскорбление, хочется отшутиться или ответить грубо.",
        "«Извините… можете тише?» — слышится уважение и конкретная просьба.",
      ],
      contactStart: 50,
      highlights: [
        {
          fragment: "глухой",
          note: "Оскорбление режет контакт",
          innerThought: "Защита: меня унижают публично.",
          contactDelta: -16,
        },
        {
          fragment: "Извините",
          note: "Мягкий вход",
          innerThought: "Можно не сразу рычать в ответ.",
          contactDelta: 12,
        },
      ],
      theirPerspective:
        "Когда слышу унижение — хочется ответить резко. Когда слышу вежливую просьбу — проще сделать тише.",
    },
    {
      type: "build",
      section: "transit-integration",
      title: "Собери короткую фразу",
      ofnrFocus: "request",
      instructions: "Подберите блоки (в транспорте часто хватает короткого наблюдения + просьбы).",
      slots: [
        { key: "observation", label: "Наблюдение" },
        { key: "feeling", label: "Чувство" },
        { key: "need", label: "Потребность" },
        { key: "request", label: "Просьба" },
      ],
      bank: [
        { id: "o1", slot: "observation", text: "Музыка из ваших наушников слышна мне очень громко." },
        { id: "o2", slot: "observation", text: "Вы ведёте себя как ужасный попутчик и не уважаете чужое пространство в вагоне." },
        { id: "f1", slot: "feeling", text: "Мне некомфортно." },
        { id: "f2", slot: "feeling", text: "Меня бесит, что вы так слушаете музыку, и я не хочу с вами делить это пространство." },
        { id: "n1", slot: "need", text: "Мне важны покой и возможность не перегружать слух чужим звуком в дороге." },
        { id: "n2", slot: "need", text: "Мне нужно поставить вас на место и унизить перед всеми за эту громкость." },
        { id: "r1", slot: "request", text: "Можете, пожалуйста, сделать громкость ниже?" },
        { id: "r2", slot: "request", text: "Соберите вещи и уйдите из вагона — я не хочу больше вас здесь видеть и слышать." },
      ],
      correct: {
        observation: "o1",
        feeling: "f1",
        need: "n1",
        request: "r1",
      },
    },
    {
      type: "reflection",
      section: "transit-integration",
      title: "На выходе",
      prompt: "Одна фраза, которую хотите попробовать в транспорте, если снова будет слишком громко?",
      placeholder: "По желанию…",
    },
  ],
};
